name: Sync tmp-data.json to data.json

on:
  push:
    paths:
      - 'tmp-data.json'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "HomeBudget Bot"
          git config --global user.email "home-budget@example.com"

      - name: Move tmp-data.json to data.json
        run: |
          cp tmp-data.json data.json
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add data.json
          git commit -m "Sync tmp-data.json → data.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
